# Generated by Django 4.0.1 on 2022-02-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udate', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Update Date')),
                ('cdate', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Created Date')),
                ('device_id', models.CharField(max_length=100, verbose_name='Device ID')),
                ('is_login', models.BooleanField(default=False, verbose_name='Is In Use Now?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('reg_user', models.CharField(max_length=100, verbose_name='Register By Username')),
                ('update_user', models.CharField(max_length=100, verbose_name='Update By Username')),
            ],
            options={
                'ordering': ['-udate'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udate', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Updated Date')),
                ('cdate', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Clinic Name')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Clinic City')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.device', verbose_name='Device')),
            ],
            options={
                'ordering': ['-udate'],
            },
        ),
    ]
